spring:
  datasource:
    url: ${Credentials.DATABASE_URL}
    username: ${Credentials.PGUSER}
    password: ${Credentials.PGPASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
