spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-95.railway.app:7626/railway
    username: ${CREDENTIAL.PGUSER}
    password: ${CREDENTIAL.PGPASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false # Set true for debugging
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)
    open-in-view: false
